### ISSUE TITLE
ctype_index missing

### ISSUE THREAD

**Issue by rolandlo** [Tekenlight/luaffifb#1]
Hi @sudheerhebbale !

Trying to get [lua-vips](https://github.com/libvips/lua-vips) work with Lua 5.3 (and 5.4) I stumbled upon your fork of luaffifb. Great work, by the way!

It turned out that lua-vips works with your fork after applying some changes to both. 

- For luaffifb what is needed is something like https://github.com/rolandlo/luaffifb/commit/8ddcf65a2888899e061a3ca6958398615695ecc7
This is needed, since your fork doesn't support things like `<ffi-metatype>.<function name>` (like `voperation.call` from `lua-vips`). 

- For lua-vips, see the commits from 2023, Aug 6 in https://github.com/rolandlo/lua-vips/commits/fix-lua-5.3

Would you consider adding an `__index` metamethod to the `ctype_mt` (like in the commit referenced above)?
I don't have much knowledge about luaffifb and the programming techniques used therein, so I can't judge by myself. I can just say that it would be pretty useful to have (in a maintained fork; I can't maintain one myself). I have used it for image manipulation in Xournal++ via Lua plugins. See also https://github.com/libvips/lua-vips/issues/9 and for a discussion and links.

**Comment by sudheerhebbale** [comment]
Hi @rolandlo 

I am not familiar with [lua-vips](https://github.com/libvips/lua-vips)
So let me state my understanding of the requirement based on the notes and code you have provided, please give your comments.

The idea is to set a metatable for a `ctype` and be able to invoke the functions within (Somewhat similar to static functions of a class in C++, the difference being unlike in C++ these methods will not be available to objects instantiated from `ctype`)

An illustrative usage will be somewhat like
```
local ctype = ffi.metatype("c type like struct S", metatable); -- metatable is the table with function references
ctype.<method>(...);

```

Cheers !!
Sudheer

**Comment by sudheerhebbale** [comment]
And ofcourse apart from static methods, they can be static members as well

**Comment by rolandlo** [comment]
> Hi @rolandlo
> 
> I am not familiar with [lua-vips](https://github.com/libvips/lua-vips) So let me state my understanding of the requirement based on the notes and code you have provided, please give your comments.
> 
> The idea is to set a metatable for a `ctype` and be able to invoke the functions within (Somewhat similar to static functions of a class in C++, the difference being unlike in C++ these methods will not be available to objects instantiated from `ctype`)
> 
> An illustrative usage will be somewhat like
> 
> ```
> local ctype = ffi.metatype("c type like struct S", metatable); -- metatable is the table with function references
> ctype.<method>(...);
> ```
> 
> Cheers !! Sudheer

Thanks for the reply. Yes, you understand correctly. Here's a minimal example that works with LuaJit and in standard Lua with the commit adding `ctype_index` (and doesn't work without this commit because of the last assertion):

```lua
local ffi = require("ffi")
local tp = ffi.metatype(
  [[ struct {} ]],
  {
    __index = {
      test = function(x) return x + 1 end,
      val = 10,
    }
  }
)

local d = tp()
assert(d.test(99) == 100)
assert(d.val == 10)
assert(tp.test(99) == 100)
assert(tp.val == 10)
```
This minimal example is inspired from https://github.com/openresty/luajit2-test-suite/blob/master/test/ffi/ffi_metatype.lua (originally from Peter Cawley's test suite in https://github.com/LuaJIT/LuaJIT-test-cleanup/blob/master/test/lib/ffi/ffi_metatype.lua)

So when a metatype `tp` has a function `test(...)` in the `__index` metamethod of its metatable that is static (in the sense that it doesn't use an object for the metatype) I want to be able to use `tp.test(...)` for applying the function and similarly for static members `val` I want to read `tp.val`.

**Comment by sudheerhebbale** [comment]
Hi ,

While testing with  [TEST CAES](https://github.com/openresty/luajit2-test-suite/blob/master/test/ffi/ffi_metatype.lua) after incorporating the changes. The following use cases appear to be very difficult to achieve

1. initializing a variable with syntax ```local f = 3LL / a```, this will require changes to parser and will require high effort. Alternate way to do the same would be ``` local f = ffi.new("long long", 3) / a```
2. Support for C++ syntax as given below will be a lot of effort to add enhancements to the compiler.
```
struct {
  static const int Z42 = 42;
  enum { Z39 = 39 };
  int x;
}]]
```
3. Support __index member supports only functions or tables,
The test case code
```
local xt = ffi.metatype("struct { }", { __index = fb })
```

can be altered as  to achieve the result

```
local xt = ffi.metatype("struct { }", { __index = function (c, n) return  fb.x end })
```
Hope these limitations will be OK for your purpose

Will do more analysis and testing before merging the changes

Cheers,
Sudheer

**Comment by rolandlo** [comment]
Yes, these limitations are OK for my purpose.

**Comment by sudheerhebbale** [comment]
The necessary changes are made
Please check

**Comment by rolandlo** [comment]
> The necessary changes are made Please check

It works all fine with Lua 5.4, thanks!
It would be great if the new version could be downloaded from the luarocks server. There is only an 8 year old [version](https://luarocks.org/modules/colesbury/luaffi) from @colesbury

**Comment by sudheerhebbale** [comment]
More work needed for making this available from luarocks.

Reoppening the issue

**Comment by sudheerhebbale** [comment]
Had to rename the package inorder to have it available from luarocks.
It is now named as luaffi-tkl

You can try installing using ```luarocks install luaffi-tkl```

**Comment by rolandlo** [comment]
Great! That works fine.
