### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by rolandlo** [Tekenlight/luaffifb#2]
As I have noticed the only thing preventing using `luaffi-tkl` on Windows (MinGW) is the fact that Windows doesn't have `execinfo.h` header and so the block

https://github.com/Tekenlight/luaffifb/blob/6a0239d4add081ca38dc57709d50c5843d9e5980/ffi.h#L22-L27

doesn't work. Removing the block or putting it into a `#ifndef _WIN32 #endif` scope makes `luaffi-tkl` work (and even `lua-vips` for the most part on top of that) on Windows (MinGW with Lua 5.4). Also the `STACK_TRACE`  macro is not used anywhere, so it could maybe also be removed. What do you think?

I have done tested the examples provided in http://luajit.org/ext_ffi_tutorial.html and they work, too.

**Comment by sudheerhebbale** [comment]
I suppose the block should be excluded for _WIN64 as well

**Comment by sudheerhebbale** [comment]
Agree that STACK_TRACE is not used anywhere
I had kept it only for debugging purposes.

Removed the block

**Comment by rolandlo** [comment]
Thanks a lot! By the way despite its name `_WIN32` also includes 64bit versions. See [here](https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170&redirectedfrom=MSDN).

**Comment by sudheerhebbale** [comment]
Have pushed the rockespec now

I had some confusion.

Please confirm if it works

**Comment by rolandlo** [comment]
Yes, it works. Thanks again!
